import type { AgentKind, SyncMethod } from "@/lib/api";

export const copy = {
  app: {
    name: "skills-hub",
    tagline: "AI Agent 技能库",
    hubHint: "当前环境的统一技能库。",
  },
  nav: {
    dashboard: "总览",
    sources: "安装来源",
    hub: "技能库",
    agents: "本机管理",
    remotes: "环境",
    settings: "设置",
  },
  dashboard: {
    title: "整理你的 AI Coding Skills",
    subtitle: "先纳管到当前环境的统一技能库，再按需同步到 Codex、Claude、Cursor 和 OpenClaw。",
    metrics: {
      hub: "技能库",
      sources: "来源",
      codex: "Codex",
      claude: "Claude",
      cursor: "Cursor",
      openclaw: "OpenClaw",
    },
    flowTitle: "下一步建议",
    flowDescription: "导入已有技能、安装新技能，或处理工具状态。",
    addSource: "添加安装来源",
    scanSkills: "导入已有技能",
    reviewHub: "查看技能库",
    syncAgents: "同步到 Agent",
    attentionTitle: "需要关注",
    attentionDescription: "来自本机状态的潜在问题。",
    conflicts: "冲突",
    missingLinks: "未同步",
  },
  sources: {
    title: "安装来源",
    subtitle: "从 GitHub、GitLab、SSH Git 或本地集合安装新技能到当前环境的统一技能库。",
    add: "添加安装来源",
    registered: "已注册来源",
    count: (value: number) => `${value} 个来源`,
    empty: "还没有安装来源。可以添加 GitLab 或 GitHub 技能仓库。",
    scanTitle: (value?: string | null) => (value ? `可安装技能：${value}` : "可安装技能"),
    scanDescription: "选择一个来源，查看可安装到本机技能库的技能。",
    scan: "扫描",
    delete: "删除",
    found: (value: number) => `发现 ${value} 个技能`,
    installSelected: (value: number) => `安装已选（${value}）`,
    installAll: "全部安装",
    chooseAndScan: "请选择一个来源并点击扫描。",
    dialogTitle: "添加安装来源",
    dialogDescription: "支持 GitHub、GitLab、SSH Git 或本地路径。",
    namePlaceholder: "来源名称，可选",
    branchPlaceholder: "分支，可选",
    adding: "正在添加来源…",
    addSuccess: "来源已添加",
    addFailed: "来源添加失败",
    deleting: "正在删除来源…",
    deleteSuccess: "来源已删除",
    deleteFailed: "来源删除失败",
    scanning: "正在扫描来源…",
    scanSuccess: "扫描完成",
    scanFailed: "扫描失败",
    installing: "正在安装到技能库…",
    installSuccess: "已安装到技能库",
    installFailed: "技能安装失败",
  },
  hub: {
    title: "技能库",
    subtitle: "当前环境统一管理的技能，按需同步到 Codex、Claude、Cursor 和 OpenClaw。",
    search: "搜索已安装技能",
    noDescription: "暂无描述",
    empty: "技能库中还没有技能。",
    refresh: "刷新",
    loading: "正在读取技能库…",
    loadFailed: "技能库读取失败",
    all: "全部",
    conflict: "冲突",
    detail: "详情",
    open: "打开目录",
    remove: "删除技能",
    removeConfirm: "会删除 Hub 中的 Skill，并移除所有由 skills-hub 管理的 Agent 链接或副本；未受管真实目录会保留。",
    removed: "技能已删除",
    removeFailed: "技能删除失败",
    files: "文件",
    readme: "SKILL.md",
    syncAll: "批量启用",
  },
  agents: {
    title: "当前环境 Skill 管理",
    subtitle: "统一管理当前环境的 Hub，并按需同步到 Codex、Claude、Cursor 和 OpenClaw。",
    sync: "同步 Agent",
    method: "同步方式",
    methodFromSettings: "同步方式来自设置",
    dryRun: "预演",
    force: "强制",
    oneClickMigrate: "纳管已有 Skill",
    migrateDescription: "把 Agent 目录里还未进入 Hub 的真实 Skill 安全纳入统一管理。",
    migrateAll: "全部纳管",
    migrateConfirmTitle: "确认纳入统一管理？",
    migrateConfirmDescription: "会先复制到技能库，再备份原目录，最后把原目录替换为链接；不会直接删除用户内容。",
    totalSkills: "已发现",
    inHub: "已在技能库",
    migratable: "待纳管",
    noMigratable: "暂无待纳管 Skill",
    migrate: "纳管",
    migrating: "正在纳管 Skill…",
    migrateSuccess: "纳管完成",
    migrateFailed: "纳管失败",
    syncing: "正在同步 Agent…",
    syncSuccess: "Agent 同步完成",
    syncFailed: "Agent 同步失败",
    distributing: "正在同步技能…",
    distributeSuccess: "技能已同步",
    distributeFailed: "技能同步失败",
    canceling: "正在取消同步…",
    cancelSuccess: "已取消同步",
    cancelFailed: "取消同步失败",
    alreadySynced: "点击取消同步",
    conflictTip: "目标工具已有同名技能，需要处理",
    loading: "正在读取工具状态…",
    loadFailed: "工具状态读取失败",
    empty: "技能库中还没有技能。可以先纳管已有技能，或从安装来源导入新技能。",
    distribute: "同步到 Agent",
    distributeDescription: "点击每个 Skill 右侧的 Agent 图标，即可同步或取消同步。",
    hubMatrix: "按 Skill 同步",
    inventory: "工具清单",
    inventoryDescription: "查看 Codex、Claude、Cursor、OpenClaw 真实目录中已有的 Skill。",
    showInventory: "查看工具清单",
    hideInventory: "收起工具清单",
    missing: "未同步",
    loadingInventory: "正在读取各工具真实技能目录…",
    inventoryEmpty: "这个工具目录下还没有技能。",
    takeover: "备份并接管",
    takeoverTitle: "备份并接管同名技能？",
    takeoverDescription: "会先把目标工具中的同名目录移动到备份目录，再同步技能库版本。",
    takeoverSuccess: "已备份并接管",
    takeoverFailed: "接管失败",
    openConflict: "打开目录",
    keepConflict: "保留现状",
  },
  remotes: {
    title: "SSH 环境",
    subtitle: "通过 SSH 在另一台电脑上执行与本机一致的 Skill 管理流程。",
    cardTitle: "环境管理",
    cardDescription: "添加 SSH 环境后，可以查看状态、传输 Skill，并同步到目标 Agent。",
    add: "添加 SSH 连接",
    addFromConfig: "从 SSH 配置选择",
    addManual: "手动添加",
    sshConfigTitle: "来自此 Mac 的 SSH 连接",
    sshConfigDescription: "读取 ~/.ssh/config 中的 Host alias，不会发起真实连接。",
    noSshHosts: "没有发现可用的 SSH Host。可以切换到手动添加。",
    enabled: "已注册",
    displayName: "显示名称，可不填",
    name: "显示名称",
    host: "SSH Host / 别名",
    hostPlaceholder: "例如：office-mac、devbox 或 192.168.1.10",
    user: "用户，可选；留空使用 SSH config 或当前用户",
    port: "端口，可选；留空使用 SSH config 或 22",
    registered: "SSH 环境",
    empty: "还没有 SSH 环境。可以添加 SSH host。",
    scan: "扫描",
    list: "对比",
    sync: "同步",
    delete: "删除",
    tools: "目标工具",
    method: "同步方式",
    methodFromSettings: "同步方式来自设置",
    deleteConfirmTitle: "删除 SSH 环境配置？",
    deleteConfirmDescription: "只会从 skills-hub 中移除该环境记录，不会删除目标机器上的技能、文件或目录。",
    deleteConfirmAction: "删除配置",
    cancel: "取消",
    adding: "正在添加 SSH 环境…",
    addSuccess: "SSH 环境已添加",
    addFailed: "SSH 环境添加失败",
    deleting: "正在删除 SSH 环境…",
    deleteSuccess: "SSH 环境已删除",
    deleteFailed: "SSH 环境删除失败",
    scanning: "正在扫描 SSH 环境…",
    scanSuccess: "SSH 环境扫描完成",
    check: "检测连接",
    checking: "正在检测连接…",
    connected: "连接成功",
    connectFailed: "连接失败",
    scanFailed: "SSH 环境扫描失败",
    listing: "正在对比环境…",
    listSuccess: "环境对比完成",
    listFailed: "环境对比失败",
    syncing: "正在同步目标环境…",
    syncSuccess: "环境同步完成",
    syncFailed: "环境同步失败",
  },
  settings: {
    title: "设置",
    subtitle: "管理全局偏好与本机路径。",
    hub: "统一技能库",
    config: "配置",
    lock: "锁文件",
    cache: "缓存",
    backups: "备份",
    logs: "日志",
    preferences: "偏好设置",
    defaultSyncMethod: "默认同步方式",
    defaultSyncMethodDescription: "工具同步和远程同步默认使用该策略。",
    saveSuccess: "设置已保存",
    saveFailed: "设置保存失败",
    loading: "正在读取设置…",
    loadFailed: "设置读取失败",
  },
  common: {
    commandPlaceholder: "搜索技能、来源、工具，或按 ⌘K 打开命令…",
    loading: "加载中…",
    retry: "重试",
    close: "关闭",
    copyPath: "复制路径",
    installed: "已安装",
    symlink: "符号链接",
    noDescription: "暂无描述",
  },
};

export function agentLabel(agent: AgentKind) {
  const labels: Record<AgentKind, string> = {
    codex: "Codex",
    claude: "Claude",
    cursor: "Cursor",
    openclaw: "OpenClaw",
  };
  return labels[agent];
}

export function syncMethodLabel(method: SyncMethod) {
  const labels: Record<SyncMethod, string> = {
    auto: "自动",
    symlink: "符号链接",
    copy: "复制",
  };
  return labels[method];
}

export function statusLabel(status: string) {
  const labels: Record<string, string> = {
    linked: "已同步",
    copied: "已同步",
    missing: "未同步",
    conflict: "冲突",
    "hub-only": "未同步",
    skipped: "已跳过",
    "dry-run": "预演",
    unlinked: "未同步",
    synced: "已同步",
    "remote-only": "仅在目标环境",
  };
  return labels[status] ?? status;
}
